# Site settings
meta:
  title: Qeewi
  description: >
    Emile Duval, Front-End Développeur.
  keywords: >
    HTML, CSS, JS, Javascript, Front-end, ESIAJ, HEAJ, Emile, Duval, Stage, Developpeur, Web, albert, jacquard, DWM, Back-end, PHP, jQuery, développement, mobile

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qeewi.io" # the base hostname & protocol for your site

# Author
author:
  name: Emile Duval
  mentra: Développeur Front-End
  email: bonjour@emileduval.be

#Google Analytics
ga:
  shortname: UA-50282848-2

# Social
social:
  - icon: twitter
    url:  https://twitter.com/QeewiDev
  - icon: github
    url:  https://github.com/EmileDu/Qeewi

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
permalink: /journal/:categories/:title

collections:
  works:
    output: true
    permalink: /casestudy/:title/

exclude : [node_modules, gulpfile.js, package.json, app, build, gulp, ressources]

linked_posts: true
